### PR TITLE
ci: add scorecard

### LINKED ISSUE #383: Add openssf scorecard
## why

This scorecard helps a lot on improving repository security integrity.

These values are also exposed to renovatebot PRs if OpenSSF is enabled

## references

- main repo https://github.com/ossf/scorecard
- https://securityscorecards.dev/#how-it-works
- example for this project https://scorecard.dev/viewer/?uri=github.com/gradle/actions
- action https://github.com/ossf/scorecard-action

### PR DESCRIPTION
**Pull request by nitrocode**
## what

- add scorecard

## why

- Show scorecard to improve metrics
- Scorecard will also show up on renovatebot PRs for this action

## references

- Closes #383

### CODE REVIEW

**Comment by nitrocode** [comment]
Thanks for merging!

**Comment by bigdaz** [comment]
@nitrocode I'm having trouble satisfying the code-review requirements for scorecard. Are you familiar with the algorithm used?

The issue is largely around bot-generated PRs and commits. Two examples:
- [This dependency-update PR](https://github.com/gradle/actions/pull/561) was generated by a bot. I reviewed and merged the PR. But the "Code Review" score for the project went down as a result.
- On each push to `main`, a workflow runs that runs npm and commits the output into the `dist` directory. [Here's an example commit](https://github.com/gradle/actions/commit/d9e39adac83414bf94447ae3ccab3d4639128362). Since this is an automated process, no review is performed and the bot commits the changes directly.

Is there a simple way I can change the process to satisfy the "code review" requirements, or am I stuck with a low score for this check?

**Comment by nitrocode** [comment]
Hi @bigdaz

I looked at the [docs](https://github.com/ossf/scorecard/blob/ea7e27ed41b76ab879c862fa0ca4cc9c61764ee4/docs/checks.md#code-review) and I see the following

> Scoring is leveled instead of proportional to make the check more predictable. If any bot-originated changes are unreviewed, 3 points are deducted. If any human changes are unreviewed, 7 points are deducted if a single change is unreviewed, and another 3 are deducted if multiple changes are unreviewed.

Your PR and Bot Commit

- https://github.com/gradle/actions/pull/561 was proposed by a bot, reviewed and merged by a user
- The example bot commit is most likely why 7 points were deducted

See the conversation in this github issue https://github.com/ossf/scorecard/issues/2450

Maybe bring this up as a separate issue (how to deal with keeping `dist/` dir up to date without losing 7 points on code review metric)? Perhaps there is a different way to solve the problem than the bot commiting directly to the HEAD branch?

**Comment by bigdaz** [comment]
Thanks for checking. I'd prefer not to make the process less convenient in order to satisfy this (somewhat arbitrary) requirement.

For now I think I'll just ignore the CodeReview portion of the scorecard.

**Pull request merged**
