### PR TITLE
Add a test for merging existing toolchains.xml

### PR DESCRIPTION
**Pull request by hfhbd**
I guess there should be more tests than the two CodeQL ones?

### CODE REVIEW

**Comment by bigdaz** [comment]
Yes, the test workflows aren't running because they currently only have a `push` trigger.
Do you see the unit-test and integ-test workflows running in your repo? Do they succeed?

**Comment by bigdaz** [comment]
Can you try pushing another commit to this PR? I don't think it will trigger the `push` workflows in this repository, but it would be nice to confirm that.

**Comment by hfhbd** [comment]
> Do you see the unit-test and integ-test workflows running in your repo? Do they succeed?

Yes, there are all green.

Yeah, pushing to this PR won't run your workflow, you need a `pull_request` trigger.

**Comment by bigdaz** [comment]
Can you please rebase this? I've updated the workflows to include `pull_request` triggers.

**Comment by bigdaz** [comment]
Thanks. [These failures](https://github.com/gradle/actions/actions/runs/8638961843) should be fixed by 30a2ee13f2ad994ba69bdd1e50160bce82e466b7.
So hopefully the next rebase will be good!

**Comment by bigdaz** [comment]
Merged. The 'dist' directory was automatically updated by c31cff66cf526c48eb5631ce4b0ee4e7564a0bb9

**Pull request merged**
